import { Product, Category, SystemSetting } from '../types/index.js';

export const INITIAL_CATEGORY: Category = {
  id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  name: 'Águas',
  slug: 'aguas',
  description: 'Águas minerais com e sem gás, galões e copos descartáveis',
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'b1000001-0000-0000-0000-000000000001',
    category_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Água Cristal 510 ml',
    slug: 'agua-cristal-510ml',
    sku: 'AGUA-510ML',
    description: 'Água mineral natural sem gás 510 ml. Fardo fechado com 12 unidades.',
    price: 1.59,
    unit: 'unidade',
    minimum_quantity: 1,
    maximum_quantity: null,
    quantity_step: 1,
    package_size: 12,
    package_label: 'fardo',
    image_url: null,
    is_active: true,
    stock_control_enabled: false,
    stock_quantity: 1000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b1000001-0000-0000-0000-000000000002',
    category_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Água Cristal 510 ml com gás',
    slug: 'agua-cristal-510ml-gas',
    sku: 'AGUA-510ML-GAS',
    description: 'Água mineral natural com gás 510 ml. Fardo fechado com 12 unidades.',
    price: 1.99,
    unit: 'unidade',
    minimum_quantity: 1,
    maximum_quantity: null,
    quantity_step: 1,
    package_size: 12,
    package_label: 'fardo',
    image_url: null,
    is_active: true,
    stock_control_enabled: false,
    stock_quantity: 1000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b1000001-0000-0000-0000-000000000003',
    category_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Água 1,5 L',
    slug: 'agua-15l',
    sku: 'AGUA-15L',
    description: 'Água mineral natural 1,5 Litros. Fardo fechado com 6 unidades.',
    price: 2.49,
    unit: 'unidade',
    minimum_quantity: 1,
    maximum_quantity: null,
    quantity_step: 1,
    package_size: 6,
    package_label: 'fardo',
    image_url: null,
    is_active: true,
    stock_control_enabled: false,
    stock_quantity: 1000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b1000001-0000-0000-0000-000000000004',
    category_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Água 5 L',
    slug: 'agua-5l',
    sku: 'AGUA-5L',
    description: 'Garrafão de água mineral natural 5 Litros. Fardo fechado com 2 unidades.',
    price: 7.49,
    unit: 'unidade',
    minimum_quantity: 1,
    maximum_quantity: null,
    quantity_step: 1,
    package_size: 2,
    package_label: 'fardo',
    image_url: null,
    is_active: true,
    stock_control_enabled: false,
    stock_quantity: 1000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b1000001-0000-0000-0000-000000000005',
    category_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Galão 20 L (refil)',
    slug: 'galao-20l-refil',
    sku: 'GALAO-20L-REFIL',
    description: 'Galão de água mineral 20 Litros para troca de vasilhame (refil).',
    price: 8.99,
    unit: 'unidade',
    minimum_quantity: 1,
    maximum_quantity: null,
    quantity_step: 1,
    package_size: null,
    package_label: null,
    image_url: null,
    is_active: true,
    stock_control_enabled: false,
    stock_quantity: 1000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b1000001-0000-0000-0000-000000000006',
    category_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Galão 20 L + casco',
    slug: 'galao-20l-casco',
    sku: 'GALAO-20L-CASCO',
    description: 'Galão de água mineral 20 Litros completo (água mineral + vasilhame novo).',
    price: 34.90,
    unit: 'unidade',
    minimum_quantity: 1,
    maximum_quantity: null,
    quantity_step: 1,
    package_size: null,
    package_label: null,
    image_url: null,
    is_active: true,
    stock_control_enabled: false,
    stock_quantity: 1000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b1000001-0000-0000-0000-000000000007',
    category_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Água 200 ml (copo)',
    slug: 'agua-200ml-copo',
    sku: 'AGUA-200ML-COPO',
    description: 'Copo de água mineral 200 ml descartável. Venda permitida apenas em múltiplos de 4 (mínimo 4, máximo 48 unidades).',
    price: 0.99,
    unit: 'unidade',
    minimum_quantity: 4,
    maximum_quantity: 48,
    quantity_step: 4,
    package_size: null,
    package_label: null,
    image_url: null,
    is_active: true,
    stock_control_enabled: false,
    stock_quantity: 1000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_SETTINGS: SystemSetting[] = [
  { id: '1', key: 'STORE_NAME', value: 'H2GO Smart', description: 'Nome da Loja', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '2', key: 'STORE_CITY', value: 'Ribeirão Branco', description: 'Cidade de Atendimento', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '3', key: 'STORE_STATE', value: 'SP', description: 'Estado de Atendimento', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '4', key: 'SHIPPING_FEE', value: '4.98', description: 'Taxa de Frete Padrão em Ribeirão Branco', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '5', key: 'CURRENCY', value: 'BRL', description: 'Moeda Padrão', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '6', key: 'STORE_ACTIVE', value: 'true', description: 'Status de Funcionamento da Loja', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '7', key: 'PAYMENT_ENABLED', value: 'false', description: 'Se pagamentos online automáticos estão ativos', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '8', key: 'ALLOW_CASH_PAYMENT', value: 'true', description: 'Permitir pagamento na entrega', is_public: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];
